name: Build ESP8266 Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Update core index
        run: arduino-cli core update-index

      - name: Install ESP8266 core
        run: |
          arduino-cli core update-index \
          --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266 \
          --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: List installed cores
        run: arduino-cli core list

      - name: Install U8g2 library
        run: |
          arduino-cli lib install U8g2

      - name: Compile ESP8266 D1 mini sketch
        run: |
          arduino-cli compile \
          --fqbn esp8266:esp8266:d1_mini \
          esp_client

      - name: Read version from Config.h
        run: |
          VERSION=$(grep -oP '(?<=#define SOFTWARE_VERSION ")[^"]+' esp_client/Config.h)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT


      - name: Create version.txt
        run: echo "${{ steps.ver.outputs.version }}" > build/version.txt

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.ver.outputs.version }}
          name: Release v${{ steps.ver.outputs.version }}
          files: |
            build/*.bin
            build/version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
